/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p3;
import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.*;
import java.net.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;


/**
 *
 * @author jordiperez
 */
public class Client_GUI extends JFrame {

    /**
     * Creates new form Xat_GUI
     */
    public JFrame window = this;
    public static final int port = 12345;
    public static final String Server_host="LocalHost";
    public MySocket socket = new MySocket(Server_host,port);
    public String name = "initial";
    //public static JTextArea chat_area, usersConnected;
    public PrintWriter out=new PrintWriter(socket.MygetOutputStream(),true);


    public Client_GUI() {
        initComponents();
        Client_GUI.Output_client output = new Output_client();
        Client_GUI.Close_client close = new Close_client();
        output.execute();
        close.execute();
    }
    class Close_client extends SwingWorker<String,Object>{
        protected String doInBackground() throws Exception{
            window.addWindowListener(new WindowAdapter(){
                public void windowClosing(WindowEvent e){
                out.print("/exit");
                out.flush();
                    try {
                        socket.close();
                    } catch (IOException ex) {
                        Logger.getLogger(Client_GUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                System.out.println("CONNECTION CLOSED");
                System.exit(0);
            }
            });
            return null;
        }
    }
    class Output_client extends SwingWorker<String,Object>{
        protected String doInBackground() throws Exception{
            BufferedReader buff= new BufferedReader(new InputStreamReader(socket.MygetInputStream()));
            String linia;
            String[] nicks = null;
            while((linia = buff.readLine())!= null ){
                
                if(linia.contains("ha marxat")){
                    nicks = linia.split(" ");
                    usuaris.remove(nicks[0]);
                    chat_area.append(linia+"\n");
                }
                else if(linia.contains("users")){
                    String[] users;
                    boolean duplicat;
                    users = linia.split("/");     
                    for(int i = 1;i<users.length;i++){
                        duplicat = false;
                        for(int j = 0;j<usuaris.getItemCount();j++){      
                            if(users[i].equals(usuaris.getItem(j))){
                                duplicat = true;
                            } 
                  
                        }
                        if(!duplicat){
                            usuaris.add(users[i]);             
                        }
                    }
                }else{
                    System.out.println(linia);
                    chat_area.append(linia + "\n");
                }
                
                
            }
            return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_panel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        usuaris = new java.awt.List();
        msg = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        chat_area = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        send = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setSize(new java.awt.Dimension(436, 420));

        title_panel.setForeground(new java.awt.Color(255, 255, 255));
        title_panel.setToolTipText("");
        title_panel.setFont(new java.awt.Font("Geneva", 1, 13)); // NOI18N

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setLabelFor(title_panel);
        title.setText("CLIENT XAT");
        title.setToolTipText("");

        javax.swing.GroupLayout title_panelLayout = new javax.swing.GroupLayout(title_panel);
        title_panel.setLayout(title_panelLayout);
        title_panelLayout.setHorizontalGroup(
            title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_panelLayout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        title_panelLayout.setVerticalGroup(
            title_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        usuaris.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        usuaris.setMixingCutoutShape(null);
        usuaris.setName(""); // NOI18N
        usuaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarisActionPerformed(evt);
            }
        });

        msg.setForeground(new java.awt.Color(204, 204, 204));
        msg.setText("Escriu aqui el seu missatge");
        msg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                msgMouseClicked(evt);
            }
        });
        msg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msgActionPerformed(evt);
            }
        });

        chat_area.setColumns(20);
        chat_area.setRows(5);
        jScrollPane1.setViewportView(chat_area);

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/jordiperez/OneDrive/Documentos/Enginyeria de Telecomunicacions/3B/SAD/online.png")); // NOI18N
        jLabel1.setText("Users online");

        send.setIcon(new javax.swing.ImageIcon("/Users/jordiperez/OneDrive/Documentos/Enginyeria de Telecomunicacions/3B/SAD/send.png")); // NOI18N
        send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sendMouseClicked(evt,out);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(usuaris, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(send, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addComponent(title_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(send)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(usuaris, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void msgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msgActionPerformed
        // TODO add your handling code here:
        String textToSend = msg.getText();
        name = textToSend;
        msg.setText("");
        this.out.println(textToSend + "\n");
        this.out.flush();
        chat_area.append(textToSend + "\n");
    }//GEN-LAST:event_msgActionPerformed

    private void usuarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarisActionPerformed

    private void msgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_msgMouseClicked
        // TODO add your handling code here:
        msg.setText("");
        msg.setForeground(Color.black);
    }//GEN-LAST:event_msgMouseClicked

    private void sendMouseClicked(MouseEvent evt, PrintWriter out) {//GEN-FIRST:event_sendMouseClicked
        // TODO add your handling code here:
         String textToSend = msg.getText();
        name = textToSend;
        msg.setText("");
        this.out.println(textToSend + "\n");
        this.out.flush();
        chat_area.append(textToSend + "\n");
    }//GEN-LAST:event_sendMouseClicked

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Client_GUI().setVisible(true);
            }
        });
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea chat_area;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField msg;
    private javax.swing.JLabel send;
    private javax.swing.JLabel title;
    private javax.swing.JPanel title_panel;
    private java.awt.List usuaris;
    // End of variables declaration//GEN-END:variables
}
